Repository TeamCodeCrafterss/CodeCrafters, pull requests merged in 2024-04, with the labels that each got.

#109 Requirements document update - Aneesh
  docs/testCaseForProjectsComponents.md
Labels: documentation

#110 Updating requirements document - Aneesh
  docs/testCaseForProjectsComponents.md
Labels: documentation

#113 Adding unit test case for getProjectData in test.js - Aneesh
  src/server/tests/test.js
  src/server/tests/{
Labels: development

#116 Users tab changes
  src/client/src/App.js
  src/client/src/components/Contracts/Contracts.css
  src/client/src/components/Contracts/Contracts.js
  src/client/src/components/EditEmployee/EditEmployee.css
  src/client/src/components/EditProject/EditProject.css
  src/client/src/components/Employees/Employees.js
  src/client/src/components/Login/Login.css
  src/client/src/components/Main/Main.js
  src/client/src/components/Projects/Projects.css
  src/client/src/components/Projects/Projects.js
  src/client/src/components/Register/Register.css
  src/client/src/components/Users/Users.css
  src/client/src/components/Users/Users.js
  src/server/tests/test.js
  src/server/tests/{
Labels: bug

#117 handled token authorization for each route
  src/client/src/components/AddContract/AddContract.js
  src/client/src/components/AddEmployee/AddEmployee.js
  src/client/src/components/AddProject/AddProject.js
  src/client/src/components/Contracts/Contracts.js
  src/client/src/components/Dashboard/Dashboard.js
  src/client/src/components/EditContract/EditContract.js
  src/client/src/components/EditEmployee/EditEmployee.js
  src/client/src/components/EditProject/EditProject.js
  src/client/src/components/EditUser/EditUser.js
  src/client/src/components/Employees/Employees.js
  src/client/src/components/Layout/Layout.js
  src/client/src/components/Login/Login.css
  src/client/src/components/Projects/Projects.js
  src/client/src/components/Settings/Settings.js
  src/client/src/components/Users/Users.js
Labels: bug

#119 Updating the GIF files in MVP as old GIF doesnt show full video - Aneesh
  docs/Before test.png
  docs/MVP.md
  docs/add_project (2).gif
  docs/project_edit-_2_.gif
Labels: documentation
