Repository TeamCodeCrafterss/CodeCrafters, pull requests merged in 2024-03, with the labels that each got.

#30 register page changes-Tarak
  src/client/src/components/Register/Register.css
  src/client/src/components/Register/Register.js
Labels: development

#35 register page changes-Tarak
  src/client/.gitignore
  src/client/src/components/Register/Register.css
  src/client/src/components/Register/Register.js
  src/server/.gitignore
  src/server/logs/logfile.log
  src/server/node_modules/.package-lock.json
  src/server/package-lock.json
  src/server/package.json
  src/server/src/api/controllers/registerUserController.js
  src/server/src/api/middlewares/mailingMiddleware.js
  src/server/src/api/routes/registerUser.js
  src/server/src/database/index.js
  src/server/src/database/schemas/userSchema.js
  src/server/src/services/registerUserService.js
Labels: development

#37 user settings page changes-Tarak
  src/client/src/components/AuthContext.js
  src/client/src/components/Login/Login.js
  src/client/src/components/Main/Main.css
  src/client/src/components/Main/Main.js
  src/client/src/components/Register/Register.js
  src/client/src/components/Settings/Settings.css
  src/client/src/components/Settings/Settings.js
  src/client/src/services/api.js
  src/client/src/services/interceptor.js
  src/server/logs/logfile.log
  src/server/src/api/controllers/loginUserController.js
  src/server/src/api/controllers/userSettingsController.js
  src/server/src/api/middlewares/authorizeMiddleware.js
  src/server/src/api/middlewares/loggingMiddleware.js
  src/server/src/api/routes/index.js
  src/server/src/api/routes/userSettings.js
  src/server/src/services/userSettingsService.js
  src/server/src/utils/jwtUtils.js
Labels: development

#51 Register login settings requirements design changes tarak
  docs/Design Document.md
  docs/Login Form Field validation 1.png
  docs/Login Form Field validation 2.png
  docs/Login Form Validation-1.png
  docs/Login Form Validation-2.png
  docs/Login Form Validation.png
  docs/Login Form.png
  docs/Login failure scenario.png
  docs/Login success scenario.png
  docs/Register Form Fields Validation.png
  docs/Register Form Validation.png
  docs/Register Form.png
  docs/Register failure scenario.png
  docs/Register success scenario.png
  docs/Regiter Form Validation-1.png
  docs/Regiter Form Validation-2.png
  docs/Regiter Form Validation-3.png
  docs/Requirements Document.md
  docs/User Settings Edit.png
  docs/User Settings Validation.png
  docs/Users.png
  docs/admin user creation data flow diagram.png
  docs/admin_user_creation.png
  docs/edit user.png
  docs/pop.md
  docs/sdp.md
  docs/user information edit.png
  docs/user information.png
  docs/user settings.png
  docs/user stories/admin user creation.md
  docs/user stories/user login.md
  docs/user stories/user registration.md
  docs/user stories/user settings.md
  docs/user stories/users.md
  docs/users data flow diagram.png
Labels: documentation

#54 Updated the data flow diagram in design document for projects component - Review needed
  docs/Design Document.md
  docs/projects_data_flow_diagram_Updated.png
Labels: documentation

#64 Users tab changes tarak
  src/client/.gitignore
  src/client/package-lock.json
  src/client/package.json
  src/client/public/index.html
  src/client/src/App.js
  src/client/src/components/ConfirmToast/ConfirmToast.css
  src/client/src/components/ConfirmToast/ConfirmToast.js
  src/client/src/components/EditUser/EditUser.css
  src/client/src/components/EditUser/EditUser.js
  src/client/src/components/Login/Login.js
  src/client/src/components/Main/Main.js
  src/client/src/components/Register/Register.js
  src/client/src/components/Settings/Settings.js
  src/client/src/components/Sidebar/Sidebar.css
  src/client/src/components/Sidebar/Sidebar.js
  src/client/src/components/Users/Users.css
  src/client/src/components/Users/Users.js
  src/client/src/services/api.js
  src/server/logs/logfile.log
  src/server/server.js
  src/server/src/api/controllers/userSettingsController.js
  src/server/src/api/controllers/usersController.js
  src/server/src/api/routes/authRoutes.js
  src/server/src/api/routes/index.js
  src/server/src/database/schemas/userSchema.js
  src/server/src/services/registerUserService.js
  src/server/src/services/usersService.js
Labels: development

#69 handled ui changes for users tab
  src/client/src/components/EditUser/EditUser.css
  src/client/src/components/EditUser/EditUser.js
  src/client/src/components/Main/Main.css
  src/client/src/components/Sidebar/Sidebar.css
Labels: bug

#70 Pushing the code for dynamic pulling of info from DBA, just with the setData lines of code and adjusted main.css
  src/client/src/components/Main/Main.css
  src/client/src/components/Projects/Projects.js
Labels: development

#71 Pushing the code with updated Table UI and table line code needed for dynamic data pulling
  src/client/src/components/Projects/Projects.js
Labels: development

#72 Added edit, delete and add buttons to the UI page
  src/client/src/components/Projects/Projects.css
  src/client/src/components/Projects/Projects.js
Labels: development

#73 Added the search functionality to the projects component
  src/client/src/components/Projects/Projects.js
Labels: development

#74 Changed to dynamic data pulling from static data
  src/client/src/components/Projects/Projects.js
  src/client/src/services/api.js
  src/server/logs/logfile.log
  src/server/src/api/controllers/projectController.js
  src/server/src/api/routes/authRoutes.js
  src/server/src/database/schemas/projectSchema.js
  src/server/src/services/projectService.js
Labels: development

#86 literative programming for register/login/users/settings components
  src/client/public/index.html
  src/client/src/App.css
  src/client/src/App.js
  src/client/src/components/ConfirmToast/ConfirmToast.css
  src/client/src/components/ConfirmToast/ConfirmToast.js
  src/client/src/components/DataContext.js
  src/client/src/components/EditUser/EditUser.css
  src/client/src/components/EditUser/EditUser.js
  src/client/src/components/Footer/Footer.css
  src/client/src/components/Footer/Footer.js
  src/client/src/components/Header/Header.css
  src/client/src/components/Header/Header.js
  src/client/src/components/Layout/Layout.css
  src/client/src/components/Layout/Layout.js
  src/client/src/components/Login/Login.css
  src/client/src/components/Login/Login.js
  src/client/src/components/Main/Main.css
  src/client/src/components/Main/Main.js
  src/client/src/components/Register/Register.css
  src/client/src/components/Register/Register.js
  src/client/src/components/Settings/Settings.css
  src/client/src/components/Settings/Settings.js
  src/client/src/components/Sidebar/Sidebar.css
  src/client/src/components/Sidebar/Sidebar.js
  src/client/src/components/Users/Users.css
  src/client/src/components/Users/Users.js
  src/client/src/index.css
  src/client/src/index.js
  src/client/src/reportWebVitals.js
  src/client/src/services/api.js
  src/client/src/services/interceptor.js
Labels: documentation, enhancement, development

#94 Delete functionality #48
  src/client/src/components/Projects/Projects.js
  src/client/src/services/api.js
  src/server/logs/logfile.log
  src/server/src/api/controllers/projectController.js
  src/server/src/api/routes/authRoutes.js
  src/server/src/services/projectService.js
Labels: development

#97 Added setData state function that updated the state_bug #96
  src/client/src/components/Projects/Projects.js
  src/server/logs/logfile.log
Labels: bug, development

#98 project add functionality
  src/client/src/App.js
  src/client/src/components/AddProject/AddProject.css
  src/client/src/components/AddProject/AddProject.js
  src/client/src/components/EditUser/EditUser.css
  src/client/src/components/Login/Login.css
  src/client/src/components/Projects/Projects.js
  src/client/src/services/api.js
  src/server/logs/logfile.log
  src/server/src/api/controllers/projectController.js
  src/server/src/api/routes/authRoutes.js
  src/server/src/services/projectService.js
  src/server/src/utils/jwtUtils.js
Labels: development
